export const Theme = {
    colors: {
        background: '#FFFFFF',
        surface: '#F8F9FA',
        surface2: '#F1F3F5',
        border: '#E9ECEF',
        accent: '#6C63FF',
        accentLight: '#EEF0FF',
        accentDark: '#5A52E0',
        text: '#1A1A2E',
        textSecondary: '#6B7280',
        textMuted: '#ADB5BD',
        success: '#10B981',
        successLight: '#D1FAE5',
        danger: '#EF4444',
        dangerLight: '#FEE2E2',
        warning: '#F59E0B',
        warningLight: '#FEF3C7',
        white: '#FFFFFF',
        black: '#000000',

        dark: {
            background: '#0F1117',
            surface: '#1A1D27',
            surface2: '#222631',
            border: '#2D3142',
            text: '#F8F9FA',
            textSecondary: '#9CA3AF',
            textMuted: '#4B5563',
        }
    },
    border: {
        width: 1,
        radius: {
            xs: 4,
            sm: 8,
            md: 12,
            lg: 16,
            xl: 24,
            full: 9999,
        },
    },
    shadow: {
        xs: {
            shadowColor: '#000000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.04,
            shadowRadius: 4,
            elevation: 1,
        },
        sm: {
            shadowColor: '#000000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.06,
            shadowRadius: 8,
            elevation: 2,
        },
        md: {
            shadowColor: '#000000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.08,
            shadowRadius: 16,
            elevation: 4,
        },
        lg: {
            shadowColor: '#000000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.10,
            shadowRadius: 24,
            elevation: 6,
        },
        accent: {
            shadowColor: '#6C63FF',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.15,
            shadowRadius: 12,
            elevation: 4,
        },
    },
    typography: {
        sizes: {
            xs: 11,
            sm: 13,
            md: 15,
            lg: 17,
            xl: 20,
            xxl: 24,
            xxxl: 32,
            hero: 48,
        },
        weights: {
            light: '300' as const,
            regular: '400' as const,
            medium: '500' as const,
            semibold: '600' as const,
            bold: '700' as const,
        },
        lineHeight: {
            tight: 1.2,
            normal: 1.5,
            relaxed: 1.8,
        },
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
        xxl: 32,
        xxxl: 48,
    },
}
